# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapreduce.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\x12\x06kmeans\"H\n\x0bTaskRequest\x12\x11\n\tcentroids\x18\x01 \x03(\x01\x12\x11\n\tdataChunk\x18\x02 \x01(\t\x12\x13\n\x0bnumReducers\x18\x03 \x01(\x05\"0\n\x0cTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\x0c\x46\x65tchRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"#\n\rFetchResponse\x12\x12\n\ndataPoints\x18\x01 \x03(\x01\x32\xc4\x01\n\rKMeansService\x12\x39\n\nProcessMap\x12\x13.kmeans.TaskRequest\x1a\x14.kmeans.TaskResponse\"\x00\x12<\n\rProcessReduce\x12\x13.kmeans.TaskRequest\x1a\x14.kmeans.TaskResponse\"\x00\x12:\n\tFetchData\x12\x14.kmeans.FetchRequest\x1a\x15.kmeans.FetchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKREQUEST']._serialized_start=27
  _globals['_TASKREQUEST']._serialized_end=99
  _globals['_TASKRESPONSE']._serialized_start=101
  _globals['_TASKRESPONSE']._serialized_end=149
  _globals['_FETCHREQUEST']._serialized_start=151
  _globals['_FETCHREQUEST']._serialized_end=178
  _globals['_FETCHRESPONSE']._serialized_start=180
  _globals['_FETCHRESPONSE']._serialized_end=215
  _globals['_KMEANSSERVICE']._serialized_start=218
  _globals['_KMEANSSERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
